name=FutabaVFD_Lib
version=1.0.0
author=sfxfs
maintainer=Hayri
sentence=A driver for Futaba and BOE CIG VFD displays.
paragraph=Supports 6-16 digit VFD modules using SPI.
category=Display
url=https://github.com/sfxfs/FUTABA-VFD-8-MD-06INKM
architectures=*
includes=FutabaVFD.h